version: '3'


services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    expose:
      - "80"
    ports:
      - 8003:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9009"
    volumes:
      - ./:/var/www/html/
    ## --------------------------------------------
    ## | 4 : database server
    ## --------------------------------------------
  mysqldb:
    image: mysql:5.7.23
    restart: always
    environment:
      - MYSQL_DATABASE=parspack
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    expose:
      - "3306"
    ports:
      - "3304:3306"
    volumes:
      - "./docker/mysql/data/:/var/lib/mysql"
      - ./docker/vol-share/:/v-share/


  ## --------------------------------------------
  ## | 8 : cache server
  ## --------------------------------------------
  redis:
    image: redis:4.0.10-alpine
    expose:
      - "6379"
    volumes:
      - ./docker/redis/default.conf:/usr/local/etc/redis/redis.conf
    command: [
      "sh", "-c",
      '
       docker-entrypoint.sh
       --requirepass "12sjb12"
      '
    ]
    ports:
    - 6377:6379

    ## --------------------------------------------
    ## | 5 : PhpMyAdmin
    ## --------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    expose:
      - '80'
      - '443'
    environment:
      - PMA_HOST=mysqldb
    volumes:
      - /docker/sessions
    ports:
    - 8005:80


